### ISSUE TITLE
Couldn't get current global ip address

### ISSUE THREAD

**Issue by Tdm012** [mkorthof/freenom-script#1]
Hi, the log file return "couldn't get current global ip address". 
I disabled ipv6 and checked my ip on internet but i don't know why the script doesn't work ...
but if i set manually "current_ip" all works, someone have an answer ?

**Comment by mkorthof** [comment]
Hi.
The script just uses dig and curl on a few domains, e.g.
```
dig -4 TXT +short o-o.myaddr.l.google.com @ns1.google.com
curl -4 https://checkip.amazonaws.co
```
If running that manually doesnt return your ip neither can the script, but if that works make sure setting
`freenom_update_ipver="4"`
You can also try ```bash -x  freenom.sh``` to see what happens
If some "getIp" lines dont work just comment them out

**Comment by Tdm012** [comment]
it's ok. i checked and somes line didn't return my ip address so i make a loop and i take line by line and i take the first ip return but thank you :D
