### ISSUE TITLE
[Question] "Can't update until..."

### ISSUE THREAD

**Issue by mcampbell** [mkorthof/freenom-script#17]
I suspect this is freenom and not your script, but any idea what this means?

```
[Wed Sep 18 06:06:53 EDT 2019] Start: Domain renewal
[Wed Sep 18 06:07:04 EDT 2019] These domain(s) were not renewed:
  Cannot renew [domain redacted] ([id redacted]) until 2019-10-30
[Wed Sep 18 06:07:04 EDT 2019] Done
```

I mean, the meaning is obvious, but ever see it before or understand what the restriction is?

**Comment by EpicestGamer** [comment]
Renewal and updating are different things. Freenom's DNS records expire after a certain time and you have to renew them or you don't have access to that domain anymore (or have to re-register it.) Freenom limits you from doing this willy-nilly though, I can't renew my domains until 14 days before they expire.

**Comment by mcampbell** [comment]
Of course, thanks.  I should have looked a little harder at what I was doing.
