### ISSUE TITLE
can Update <domain> A record with another ip?

### ISSUE THREAD

**Issue by esrrhs** [mkorthof/freenom-script#18]
-u    Update <domain> A record with current ip
                  add [-s] to update <Subdomain>
                  add [-f] to force update on unchanged ip

hi,  my script is running in another machine, so I want to update another ip to the dns record, not current ip. can you add some feature to help this?

like this ./freenom.sh  -u xxx.tk -s www -f -4 -ip 111.222.333.444

**Comment by mkorthof** [comment]
Sounds like a good idea, I'll see if I can add it -- Thanks

**Comment by esrrhs** [comment]
@mkorthof 👍

**Comment by mkorthof** [comment]
added
