### ISSUE TITLE
Update all domains ip address

### ISSUE THREAD

**Issue by copostic** [mkorthof/freenom-script#19]
Hello,

Is there a way to update the ip address on all my domains once and for all ? Or a param in the config that allow us to specify a list of domains to update? 
Because otherwise I have to make as much commands as I have domains. 

Regards

**Comment by mkorthof** [comment]
I'll see if I can add this in the near future, thanks for the suggestion

**Comment by mkorthof** [comment]
In the new version coming up I've added `[-u -a]` but not sure how useful it is, since it updates *all* domains AND records in an account. I like it for testing though so I'll leave it in as 'undocumented' test feature.

**Comment by copostic** [comment]
Thanks a lot, I will use it to update all my domains once and for all as they all points to the same server 😄
