### ISSUE TITLE
No output at all

### ISSUE THREAD

**Issue by janmoehl** [mkorthof/freenom-script#21]
Hello,
nice work. Sadly, even listing the own domains doesn't show any entry. I tried other scripts, too - but they didn't work for me as well. Did freenom recently changed their website?

No Domains are listed, and no errors or other entries found in logfile...
```
>>> /usr/local/bin/freenom.sh -l

Listing Domains and ID's...

>>> cat /var/log/freenom/freenom.log
>>> bash --version
GNU bash, Version 5.0.11(1)-release (x86_64-pc-linux-gnu)
```

**Comment by bl00dy1837** [comment]
It works for me. 
But its slow.
Try to test the script with 'bash -x freenom.sh -l" so you can see every step of the script.

**Comment by janmoehl** [comment]
:+1: thanks for the tip. The script failed to do the login. After changing my password, which contained non alphanummeric characters (in this case `'`. `#`, `>`, `-`, `{` and `;`) the login was successful.

Now i'm stuck at `Error: Could not get current local ip address`, which occurs for two of three runs. When the ip is found, the dns entry on freenom.com get updated successfully. Will look for this error later.

By the way, 
https://github.com/mkorthof/freenom-script/blob/102e2d5170b7c5cbf2e8216c3969585b85765cd6/freenom.sh#L285
prints debug messages if you use ipv6, even if debugging is turned off.

**Comment by janmoehl** [comment]
Don't know why, but  if one of these entries is picked, the script can't get the ip (tested it for ipv4 and ipv6, notused/tested dig):
```
ipCmd+=("curl -%ipv% -A %agent% -m 10 -s http://checkip.dns.he.net")
ipCmd+=("curl -%ipv% -A %agent% -m 10 -s https://cgi1.apnic.net/cgi-bin/my-ip.php")
ipCmd+=("curl -%ipv% -A %agent% -m 10 -s ipv%ipv%.test-ipv6.com/ip/?callback")
ipCmd+=("curl -4 -A %agent% -m 10 -s http://ip.taobao.com/service/getIpInfo.php?ip=myip")
```
Can you confirm this? When i comment these lines out, it works great.

**Comment by mkorthof** [comment]
Thanks @janmoehl, will look into password not being escaped correctly. I've removed the DEBUG line

You list all ip checks with `freenom.sh -i`
Try testing manually like `curl http://checkip.dns.he.net`  (or `curl -6` ) and if its not working there might be an issue between you and that ipcheck.
If a check is not working just remove the ipCmd line.

Also you can see details about what the script is doing using `freenom.sh -r -a -debug`

**Comment by mkorthof** [comment]
Password is properly escaped now; set password to chars mentioned and could successfully tested login now.

**Comment by janmoehl** [comment]
I discovered my ISP is using DS-lite, which maybe could be the reason, why some ip-tests failed (and is definitely the reason, why the domain doesn't work :disappointed:). But thanks for the quick support.
