### ISSUE TITLE
Renew always failed

### ISSUE THREAD

**Issue by boolking** [mkorthof/freenom-script#23]
renewDateOkay is local variable in func_renewDate and can't be accessed in func_renewDomain, so func_renewDomain will always be skipped.

After moving renewDateOkay out of func_renewDate and remove local, renew will work.

**Comment by bl00dy1837** [comment]
thanks for the hint. can confirm the bug and the fix

**Comment by vinanrra** [comment]
> 
> 
> renewDateOkay is local variable in func_renewDate and can't be accessed in func_renewDomain, so func_renewDomain will always be skipped.
> 
> After moving renewDateOkay out of func_renewDate and remove local, renew will work.

Can you paste the code?

**Comment by mkorthof** [comment]
@boolking thanks for noticing and reporting

@vinanrra ive added a note to README.md
