### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mvez73** [mkorthof/freenom-script#24]
When i run the script with "freenom.sh -l" i have an error.
Error: Login - token failure (curl error code: 127)

I'm sure the email and the password are correct.

Another thing, if i try to go to this page "https://api.freenom.com/v2/domain/list" i got a dialog box to log in but it doesn't work. I can't login. Maybe it's the same reason why i got an error with your script...

**Comment by mvez73** [comment]
I found the problem. Curl wasn't installed... Sorry for the inconvenience

**Comment by mvez73** [comment]
Finally i have another error:
Error: Could not get current local ip address
I can't figure out what's wrong. If i try "sudo freenom.sh -u -m 1.2.3.4 domain.tk" it works. So the connection and the the update are working but for a reason that i ignore, the script don't get my ip. Am i supposed to do something else thant just "sudo freenom.sh -u domain.tk"?

*edit* I installed dnsutils to have dig and now it works. But why it wasn't working with only curl? Maybe i missed the part that say what is need to make the script working but if not, you could add those informations to the README.md. I didn't have neighter curl nor dnsutils installed. If i knew it i wouldn't bother you. Thanks and sorry for my bad english i speak french.

**Comment by mkorthof** [comment]
there's an option in conf to use either dig or curl to get current ip, default is both
i guesss you could also add an own command instead (using ipCmd)
