### ISSUE TITLE
Won't update "sub-subdomain"

### ISSUE THREAD

**Issue by penguin321** [mkorthof/freenom-script#29]
I tried to update a part1.part2.domainname.tk. So my command is: 

> sudo bash freenom.sh -u domainname.tk -s www.cloud
 
But it won't add or update something...

**Comment by mkorthof** [comment]
Thanks for reporting.

I forgot to take the . (dot) into account as valid character, so the script will ignore the subdomain and update (apex) domain.

To fix change:

https://github.com/mkorthof/freenom-script/blob/ecb63a83920a8d137bd58c2c97fbe7a21f4bcece/freenom.sh#L250
to
``` bash
  if [[ ! "$freenom_subdomain_name" =~ ^[^-][a-zA-Z0-9\.-]+$ ]]; then
```

..or wait for next commit.
