### ISSUE TITLE
Script finished with errors

### ISSUE THREAD

**Issue by ghost** [mkorthof/freenom-script#3]
The script is not working for me.:
```[Tue 26 Mar 20:44:49 GMT 2019] Start - Update IP
[Tue 26 Mar 20:45:19 GMT 2019] Update failed (hagamosunahuel.ga 1234567890)
[Tue 26 Mar 20:45:19 GMT 2019] Done  - with errors
[Tue 26 Mar 21:52:21 GMT 2019] Start - Update IP
[Tue 26 Mar 21:52:52 GMT 2019] Update failed (mucierla.ga 1234567890)
[Tue 26 Mar 21:52:52 GMT 2019] Done  - with errors
[Wed 27 Mar 00:33:20 GMT 2019] Start - Update IP
[Wed 27 Mar 00:33:46 GMT 2019] Update failed (homework-manager.ml 1234567890)
[Wed 27 Mar 00:33:46 GMT 2019] Done  - with errors
```

thanks for your work! <3

**Comment by mkorthof** [comment]
The script failed to update dns record in clientarea and freenom did not give back a result containing your current ip. Try `freenom.sh -e` or check "freenom.errorUpdateResult.html" to see the response.

Make sure you're using latest version and and/or try enabling debug ("debug=1" in script/conf) to see where it fails.

**Comment by ghost** [comment]
@mkorthof Can we get into a chat to fix this? honestly I never check github so it's kind of a burden.

**Comment by mkorthof** [comment]
You could try latest version I just pushed to see if that fixes your issue.
If not feel free to open a new issue providing `freenom.sh -e` and debug output.
