### ISSUE TITLE
update results in duplicate A records instead of replacing the old record

### ISSUE THREAD

**Issue by jiahaoliang** [mkorthof/freenom-script#30]
I am a newbie here don't know how to produce logs exactly.

I set up freenom.sh with cron to update dynamic ip periodically on my home server.  Recently I observe when the dynamic ip changes, freenom.sh does not update the existing A record with the new ip. Instead, it adds a new A record with the new ip, leave the old A record untouch. As a result, there are both new and old records on the DNS server which causing ambiguous result.

Example:

DNS record:
example.com  A 120.\*.\*.11

Dynamic ip changes to 120.\*.\*.22
Do operation: freenom.sh -u example.com

Expected result:
DNS record:
example.com  A 120.\*.\*.22

Actual result:
DNS record:
example.com  A 120.\*.\*.22
example.com  A 120.\*.\*.11

The dns record I check it directly from the freenom client area webpage. So it could not be the problem with my local dns.

**Comment by jiahaoliang** [comment]
The weird thing is it only happens from time to time.

**Comment by mkorthof** [comment]
Yeah, I noticed this too (with apex record).
Try updating to latest commit I just pushed and see if it still happens.

**Comment by jiahaoliang** [comment]
> Yeah, I noticed this too (with apex record).
> Try updating to latest commit I just pushed and see if it still happens.

Will do. 

Thanks for the reply.

**Comment by jiahaoliang** [comment]
@mkorthof I have deployed the lastest script on my server whose dynamic IP changes every day. Don't see this issue any more so far for 15 days.

**Comment by mkorthof** [comment]
@jiahaoliang thats good to hear 👍🏻Thanks for testing
