### ISSUE TITLE
$freenom_oldcurl_force option is not working

### ISSUE THREAD

**Issue by jiahaoliang** [mkorthof/freenom-script#31]
https://github.com/mkorthof/freenom-script/blob/d5c9a614eec27aafd67b21335ce1731686695ec3/freenom.sh#L39

In this commit, the script checks the $freenom_oldcurl_force before actually source the conf file. As a result, the option will never take effect. I was looking to make a pull request, but due to the complexity of the script I am not sure the correct place to put the option checking though.

**Comment by jiahaoliang** [comment]
Also the else part here, overrides the curl version check before if freenom_oldcurl_force is not set.
https://github.com/mkorthof/freenom-script/blob/d5c9a614eec27aafd67b21335ce1731686695ec3/freenom.sh#L41

I guess the correct workflow should be 
1. source conf file
2. check where $freenom_oldcurl_force is set
3.1 if set, enforce oldCurl support
3.2 if not, check curl version to see oldCurl support is needed

**Comment by mkorthof** [comment]
Thanks for pointing that out, moved $freenom_oldcurl_force
