### ISSUE TITLE
Error: Could not get current local ip address

### ISSUE THREAD

**Issue by nonconformistqi** [mkorthof/freenom-script#32]
/usr/local/bin/freenom.sh -u ****8.tk
result:Error: Could not get current local ip address

**Comment by mkorthof** [comment]
Did you check https://github.com/mkorthof/freenom-script/#ip-address ?
If that doesnt fix your issue, run: `/usr/local/bin/freenom.sh -u ****8.tk -debug` and paste output

**Comment by MmAaXx500** [comment]
I have a similar issue with ipv6 updates. With ipv4 works fine.
In config, I didn't change anything except email and password.

Command: `bash freenom.sh -c freenom.conf -6 -u ***.ga`
Output: 
```
DEBUG: 18:05:50 sortIpCmd skip=0 i=0 ipCmd=curl -%ipv% -A %agent% -m 10 -s https://diagnostic.opendns.com/myip
DEBUG: 18:05:50 sortIpCmd skip=0 i=1 ipCmd=curl -%ipv% -A %agent% -m 10 -s https://www.ripe.net/@@ipaddress
DEBUG: 18:05:50 sortIpCmd skip=0 i=2 ipCmd=curl -%ipv% -A %agent% -m 10 -s http://ipv6-test.com/api/myip.php
DEBUG: 18:05:50 sortIpCmd skip=0 i=3 ipCmd=curl -%ipv% -A %agent% -m 10 -s http://checkip.dns.he.net
DEBUG: 18:05:50 sortIpCmd skip=0 i=4 ipCmd=curl -%ipv% -A %agent% -m 10 -s https://cgi1.apnic.net/cgi-bin/my-ip.php
DEBUG: 18:05:50 sortIpCmd skip=0 i=5 ipCmd=curl -%ipv% -A %agent% -m 10 -s ipv%ipv%.test-ipv6.com/ip/?callback
DEBUG: 18:05:50 sortIpCmd skip=1 i=6 ipCmd=curl -4 -A %agent% -m 10 -s https://checkip.amazonaws.com
DEBUG: 18:05:50 sortIpCmd skip=0 i=8 ipCmd=dig -%ipv% TXT +short o-o.myaddr.l.google.com @ns1.google.com
DEBUG: 18:05:50 sortIpCmd skip=1 i=9 ipCmd=dig -4 +short myip.opendns.com @resolver1.opendns.com
DEBUG: 18:05:50 sortIpCmd skip=1 i=11 ipCmd=dig -4 +short myip.opendns.com @resolver3.opendns.com
DEBUG: 18:05:50 sortIpCmd skip=1 i=13 ipCmd=dig -4 +short whoami.akamai.net @ns1-1.akamaitech.net
freenom.sh: line 338: RANDOM%0: division by 0 (error token is "0")
freenom.sh: line 338: RANDOM%0: division by 0 (error token is "0")
freenom.sh: line 338: RANDOM%0: division by 0 (error token is "0")
```

In freenom.log: 
```
[Wed 12 Aug 2020 06:05:50 PM CEST] Start: Update ip
[Wed 12 Aug 2020 06:05:50 PM CEST] Could not get current local ip address
```

**Comment by mkorthof** [comment]
@MmAaXx500 thanks for the debug output

The following small changes should fix the issue:

move `ipCmdSorted=()` from L349 to L346
https://github.com/mkorthof/freenom-script/blob/2fd8b993c0ec73ae6cbb22c322623438b3114ba7/freenom.sh#L349

change:
https://github.com/mkorthof/freenom-script/blob/2fd8b993c0ec73ae6cbb22c322623438b3114ba7/freenom.sh#L362

to:
``` bash
ipCmdSorted+=("${ipCmd[$i]//\%ipv\%/$freenom_update_ipv}")
```

**Comment by MmAaXx500** [comment]
Thanks @mkorthof!
Working properly!

In ipv6 mode, there are some debug output without the debug switch (like above) (from L355). But that's another story. Should I open a new issue about that?

**Comment by mkorthof** [comment]
Good to hear.

> In ipv6 mode, there are some debug output without the debug switch (like above) (from L355). But that's another story. Should I open a new issue about that?

Thats ok, did change it for the next commit (fixes other ipcheck thingy too).
