### ISSUE TITLE
Error: setting "freenom_email" is missing in config

### ISSUE THREAD

**Issue by sychowaves** [mkorthof/freenom-script#35]
Greetings ... it is not possible to configure the freenom account and password in the freenom.conf file basically I have changed it several times and it does not read the mentioned file.
Ubuntu Server Focal 20.04

```
##########################
# CONFIGURATION SETTINGS #
##########################

##############
# Login data #
##############

# Set variables for email/password -OR- source a "secrets" file
# Examples:
#   freenom_email="myemails@gmail.com" #My email here and not working
#   freenom_passwd="xxxxxxxxxxx" # My Pass here and not working
#   source "/home/${LOGNAME}/.secret/.freenom"

freenom_email="Mail@notworkin.com"    **Try here maybe and not work**
#freenom_passwd="passsnotwork"

```
Any suggestion I am doing something wrong I have been guided by what I read
Thankful & Greetings
regards!!

**Comment by ghost** [comment]
I had this issue.

After editing your config file, run this command to copy the file to the expected place:

`sudo cp freenom.conf /usr/local/etc/freenom.conf`

**Comment by mkorthof** [comment]
@sychowaves 
You need to have an uncomment freenom_email setting in config, so no # in front.
Location can same dir as script, in {/usr/local,}/etc/freenom.conf or anywhere you like (with `freenom.sh -c  /path/to/conf`)
Running the installer with `make install` does this automatically

See [configuration](https://github.com/mkorthof/freenom-script#configuration) for details
