### ISSUE TITLE
Update subdomains using systemd

### ISSUE THREAD

**Issue by LexNastin** [mkorthof/freenom-script#36]
I have 3 subdomains i want to update and i can't seem to find any way to do so with systemd, anything you can suggest?

**Comment by mkorthof** [comment]
I'm not sure systemd supports more than one variable. If not, you'd need a service unit with `-s` added in `ExecStart` and timer per (sub)domain. Alternatively use cron instead.

**Comment by LexNastin** [comment]
Ok, will try. Thanks 🙂
