### ISSUE TITLE
Running the script automatically through cron does not work

### ISSUE THREAD

**Issue by nmbizao** [mkorthof/freenom-script#4]
Hi there, I have the following on /etc/cron.d/freenom
*/10 * * * * root bash '/usr/local/bin/freenom.sh -u domain.name -s www'

freenom.log, freenom.ip are not created in /var/log/
syslog shows the following:
Mar 31 17:45:01 hostname CRON[9789]: (root) CMD (bash '/usr/local/bin/freenom.sh -u domain.name -s www')
Mar 31 17:45:02 hostname sendmail[9793]: x2VGj2VA009793: from=root, size=400, class=0, nrcpts=1, msgid=<201903311645.x2VGj2VA009793@host.name>, bodytype=8BITMIME, relay=root@localhost
Mar 31 17:45:02 hostname sm-mta[9794]: STARTTLS=server, relay=localhost [127.0.0.1], version=TLSv1.2, verify=NOT, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256/256
Mar 31 17:45:02 hostname sendmail[9793]: STARTTLS=client, relay=[127.0.0.1], version=TLSv1.2, verify=FAIL, cipher=ECDHE-RSA-AES256-GCM-SHA384, bits=256/256
Mar 31 17:45:02 hostname sm-mta[9794]: x2VGj2ti009794: from=<root@host.name>, size=652, class=0, nrcpts=1, msgid=<201903311645.x2VGj2VA009793@host.name>, bodytype=7BIT, proto=ESMTPS, daemon=MTA-v4, relay=localhost [127.0.0.1]
Mar 31 17:45:02 hostname sendmail[9793]: x2VGj2VA009793: to=root, ctladdr=root (0/0), delay=00:00:00, xdelay=00:00:00, mailer=relay, pri=30400, relay=[127.0.0.1] [127.0.0.1], dsn=2.0.0, stat=Sent (x2VGj2ti009794 Message accepted for delivery)
Mar 31 17:45:02 hostname sm-mta[9795]: x2VGj2ti009794: to=<root@host.name>, ctladdr=<root@host.name> (0/0), delay=00:00:00, xdelay=00:00:00, mailer=local, pri=30927, dsn=2.0.0, stat=Sent

Same results with:
*/10 * * * * root bash -c 'sleep $((RANDOM \% 15))m; /usr/local/bin/freenom.sh -u example.com'

Running the script manually works.
Am I doing something wrong?

**Comment by mkorthof** [comment]
Hi,

It tells you on the first line that cron started the script. If I'd have to guess it errors out shortly after and mails the output to root@localhost Maybe see what it says? (`mail` as root or view "/var/mail/root")

Alternatively you could create a cron and redirect stdout to a file, smth like:
``` */1 * * * * /usr/local/bin/freenom.sh -u domain.name -s www >/tmp/freenom.log 2>&1```

If running it manually also doesn't generate log files it might not be able to write to "$out_path" for some reason (not run as root? missing 'basename' bin? etc).

**Comment by nmbizao** [comment]
Hi,

Just for reference, /var/mail/root was outputting:
bash: /usr/local/bin/freenom.sh -u domain.name -s www: No such file or directory

Removing the ' ' from cron did the trick.

Thank you for your answer!
