### ISSUE TITLE
Error: config file not specfied when absolute path gived since #d5c9a61

### ISSUE THREAD

**Issue by xianren78** [mkorthof/freenom-script#41]
from this commit [#d5c9a61](https://github.com/mkorthof/freenom-script/commit/d5c9a614eec27aafd67b21335ce1731686695ec3)

sample:

`# /root/freenom-script/freenom.sh -c /root/freenom-script/freenom.conf -r -a`
`Error: config file not specfied, try "freenom.sh -h"`

debian10

**Comment by mkorthof** [comment]
Thanks for letting me know. It can be fixed by adding one char:

``` diff
diff --git a/freenom.sh b/freenom.sh
index 2445ca5..a5fa4dd 100755
--- a/freenom.sh
+++ b/freenom.sh
@@ -55,7 +55,7 @@ for i in "$@"; do
     continue
   else
     if [ "$c" -eq 1 ]; then
-      if printf -- "%s" "$i" | grep -Eq -- "\-"; then
+      if printf -- "%s" "$i" | grep -Eq -- "^\-"; then
         echo "Error: config file not specfied, try \"$scriptName -h\""
         exit 1
       fi
```

Ill update the repo later today.
