### ISSUE TITLE
Option to modify the time period of renewal

### ISSUE THREAD

**Issue by gopaljigaur** [mkorthof/freenom-script#44]
The script works fine and I can list my domains. But I noticed that there isn't any script option to configure the time duration for which the domain will be renewed. The default time is 3 months on freenom.com. I went through the code and realized that the script renews the domain for 12 months most of the time. Is there any configuration to change this default time to a longer period (say 6 months or 8 months)? Or will this feature be implemented in future updates?

**Comment by mkorthof** [comment]
Freenom decides the renewal period for free domains. I believe it differs per TLD they offer.

**Comment by gopaljigaur** [comment]
I have renewed two domains last month, and I was able to choose the renewal period on their website. So, freedom does not automatically decide the renewal period of the domains. Just like when registering for a new domain you get the option of selecting the time period, during renewal also there are similar options in the drop-down menu. Please don't just close issues like that without confirming the problem scenario.

**Comment by mkorthof** [comment]
Not sure what you want here, you mention a longer period than 12M (not possible) and a _LONGER_ default of 6M or 8M(?). The script just picks the longest period from list: `<option value="12M">12 Months @ FREE </option>`
Feel free to change `$renewalPeriod` or make it configurable, PR's are welcome.
