### ISSUE TITLE
Errors when listing or renewing domains

### ISSUE THREAD

**Issue by carlosnewmusic** [mkorthof/freenom-script#45]
sudo freenom.sh -l
[sudo] password for user:
DEBUG:           debug=1 c_exOpts=
DEBUG:  conf     scriptConf=/usr/local/etc/freenom.conf

Listing Domains and ID's...

DEBUG:          args         debug=1 c_exOpts=
DEBUG:          args         1=-l 2= 3= 4= 5= 6= 7= 8= 9=
DEBUG:          opts/conf    freenom_out_dir=/var/log/freenom freenom_out_mask=freenom out_path=/var/log/freenom/freenomDEBUG:          opts/conf    freenom_domain_name= freenom_domain_id= freenom_subdomain_name=
DEBUG:          opts/conf    freenom_static_ip=
DEBUG:          action       freenom_update_ip=0 freenom_update_force=0 freenom_update_manual=0 freenom_update_all=0
DEBUG:          action       freenom_list_records=0 freenom_list=1 freenom_list_renewals=0
DEBUG:          action       freenom_renew_domain=0 freenom_renew_all=1
DEBUG:          logintoken   cookie_file=/tmp/tmp.2wefMlm3oA
DEBUG: 04:12:21 logintoken   curl clientarea token=TokenChangedForSecurity (retry=1/3 http_code=200 errCount=0)
Error: Login failed, incorrect details
DEBUG: 04:12:23 func_cleanup cookie_file=/tmp/tmp.2wefMlm3oA

LOG:
[vie jun 18 16:32:56 CEST 2021] Start: Domain renewal
[vie jun 18 16:33:24 CEST 2021] These domain(s) were not renewed: 
  Cannot renew "domain.xx" (1076807386) until 2021-10-03
  Cannot renew "domain.xx" (1055596500) until 2022-01-21
[vie jun 18 16:33:24 CEST 2021] These domain(s) failed to renew: 
  Cannot renew "domain.xx" (1045224491), renewal period not found
[vie jun 18 17:12:28 CEST 2021] Start: Domain renewal
[vie jun 18 17:12:32 CEST 2021] Error: Login failed, incorrect details
[vie jun 18 17:14:46 CEST 2021] Start: Domain renewal
[vie jun 18 17:14:51 CEST 2021] Error: Login failed, incorrect details
[vie jun 18 17:30:53 CEST 2021] Start: Domain renewal
[vie jun 18 17:30:57 CEST 2021] Error: Login failed, incorrect details
[sáb jun 19 04:12:19 CEST 2021] Start: Domain renewal
[sáb jun 19 04:12:23 CEST 2021] Error: Login failed, incorrect details

**Comment by mkorthof** [comment]
Look like the script is unable to login
