### ISSUE TITLE
Issue with the config file.

### ISSUE THREAD

**Issue by adamdived** [mkorthof/freenom-script#47]
Hello. I git-cloned the script on my Debian server in a temp dir. I followed the instructions. I've made the changes requested in the freenom.conf file, like email and password. But when I try to call one of the examples like "./freenom.sh -r mydomain.tk" it says "Error: setting "freenom_email" is missing in config". But I did compile it as requested and uncommented out. What am possible doing wrong?

**Comment by PiotrDabrowskey** [comment]
Hi! Have you edited the `freenom.conf` inside your cloned repo directory or `/usr/local/etc/freenom.conf`? [Configuration](https://github.com/mkorthof/freenom-script#configuration) section states it can be either of the location, but for me the latter worked. You may give it a try.

**Comment by adamdived** [comment]
Yes thank you. It works perfectly now. My bad.

**Comment by PiotrDabrowskey** [comment]
Great! Please, close the issue if it fully solved your problem :)

**Comment by mkorthof** [comment]
Hi,
Having conf and script in same dir should work but you can also use **'-c'** (or move conf to .sh)

EXAMPLES:
            ./freenom.sh -r example.com
            **./freenom.sh -c /etc/mycustom.conf -r -a**
            ./freenom.sh -u example.com -s mail
