### ISSUE TITLE
[Feature Request] Docker

### ISSUE THREAD

**Issue by JourneyOver** [mkorthof/freenom-script#57]
Pretty much title;

Would love to see this made for easy deployment :D

**Comment by mkorthof** [comment]
You could try something like this  for example:

```
$ docker build -t freenom-script:latest -f- . <<EOF
FROM debian:stable-slim
ARG DEBIAN_FRONTEND=noninteractive
ARG DEBCONF_NOWARNINGS="yes"
COPY freenom.sh /usr/local/bin/
COPY freenom.conf /usr/local/etc/
RUN apt-get -yq update && apt-get -yq install --no-install-recommends curl ca-certificates bind9-dnsutils && rm -rf /var/lib/apt/lists/* 
USER nobody
ENTRYPOINT [ "/usr/local/bin/freenom.sh" ]
EOF
```

and then run it:

`docker run --rm --env freenom_email="you@example.com" --env freenom_passwd="yourpassword" freenom-script -l`

I'll add these instructions to the repo.

**Comment by mkorthof** [comment]
If you (or anyone else) wants to spent time on a better Dockerfile, a PR would be welcome
