### ISSUE TITLE
How do I update DNS-Record for all domains

### ISSUE THREAD

**Issue by RichardBeisser** [mkorthof/freenom-script#59]
Hello,

is it possible to update the A-record with the ip for all domains?
How do I set up a systemd-service for this?

In conf-File, there is option
freenom_update_all="1"        # [0/1] arg "-a"
But freenom.sh -h doesnt know such an option/opportunity, for example for running it once

====================================

Do you know that the script fails when one of these options set to 1:
freenom_list="0"              # [0/1] arg "-l"
freenom_list_renewals="0"     # [0/1] args "-l -d"
freenom_list_records="0"      # [0/1] arg "-z"

--> in freenom.log there is only a entry like the following one if one of the options is set to 1
[Sa 27. Aug 23:47:24 CEST 2022] [17324] Start: Domain renewal
or
[Sa 27. Aug 23:48:31 CEST 2022] [17324] Error: Domain renewal - No Domain ID ""

**Comment by mkorthof** [comment]
See #19

**Comment by RichardBeisser** [comment]
> See #19

would you be so kindly and explain how to use the update-all-domain feature together with scheduling?
The docu
https://github.com/mkorthof/freenom-script#scheduling
only describes how to add an systemd-service for 1 domain
Thanks.
