### ISSUE TITLE
check ipv6 with checkip.amazonaws.com is invalid

### ISSUE THREAD

**Issue by ef6** [mkorthof/freenom-script#6]
```sh
$curl -6 -v https://checkip.amazonaws.com
* Couldn't resolve host 'checkip.amazonaws.com'
```

**Comment by mkorthof** [comment]
should be fixed in latest version

**Comment by smcgu** [comment]
This issue appears to still be present or it has returned.

```
$ curl -6 checkip.amazonaws.com
curl: (6) Could not resolve host: checkip.amazonaws.com

$ curl -6 icanhazip.com
2607:XXXX:XXXX:XXXX::XXX
```

**Comment by mkorthof** [comment]
@buck3tsec make sure your config is correct. That endpoint should be listed as ipv4 only:

`ipCmd+=("curl -4 -A %agent% -m 10 -s https://checkip.amazonaws.com")`

You can confirm this by running `freenom.sh -i`
