### ISSUE TITLE
Freenom Domain Listing Error (Curl Error Code:28)

### ISSUE THREAD

**Issue by LordNikon82** [mkorthof/freenom-script#62]
Hello,

I just stumbled upon this scrip which would be a perfect fit for my use case but I am running into an issue when testing after the initial setup.
When executing freedom.sh -l curl run into an error as shown in the debug below:

sudo freenom.sh -l
DEBUG:           debug=1 c_exOpts=
DEBUG:  conf     scriptConf=/usr/local/etc/freenom.conf
Warning: No MTA found, cant send email

Listing Domains and ID's...

DEBUG:          args         debug=1 c_exOpts=
DEBUG:          args         1=-l 2= 3= 4= 5= 6= 7= 8= 9=
DEBUG:          opts/conf    freenom_out_dir=/var/log/freenom freenom_out_mask=freenom out_path=/var/log/freenom/freenom
DEBUG:          opts/conf    freenom_domain_name= freenom_domain_id= freenom_subdomain_name=
DEBUG:          opts/conf    freenom_static_ip=
DEBUG:          action       freenom_update_ip=0 freenom_update_force=0 freenom_update_manual=0 freenom_update_all=0
DEBUG:          action       freenom_list_records=0 freenom_list=1 freenom_list_renewals=0
DEBUG:          action       freenom_renew_domain=0 freenom_renew_all=0
DEBUG:          logintoken   cookie_file=/tmp/tmp.Mjtj7H2HUD
Error: Login token - failure (curl error code: 28)
DEBUG: 12:04:50 func_cleanup cookie_file=/tmp/tmp.Mjtj7H2HUD

Can you please assist me to get that working?
Thank you & Greets 

Stephan

**Comment by mkorthof** [comment]
Hi,

Looks like https://my.freenom.com times out.
```
$ man curl|grep 28
       28     Operation timeout. The specified time-out period was reached according to the conditions.
```
Test curl manually, resolve my.freenom.com ..etc

I've had DNS issues myself where the domain did not resolve correctly. 

You could try to test with docker and freenoms own public dns:
`docker run --rm --dns 80.80.80.80 -e freenom_email=foo@example.com -e freenom_passwd="bar" ghcr.io/mkorthof/freenom-script:latest -debug -l`
