### ISSUE TITLE
This work on Ubuntu?

### ISSUE THREAD

**Issue by santydesignscr** [mkorthof/freenom-script#64]
I try to use the script but not working for me, I am using a KVM Ubuntu VPS
![image](https://user-images.githubusercontent.com/88201812/208263233-b4455c09-d117-46c2-851a-1c38443b4188.png)

**Comment by santydesignscr** [comment]
If not, how I can unistall?

**Comment by santydesignscr** [comment]
Ohh it works, Its slow, Idk why? beacuse my vps is powerfull (6 cores, 16gb ram)

**Comment by mkorthof** [comment]
See readme on how to uninstall, same for how to change 'sleeps' between http requests. 
Could be freenom.com too, they're not the most performant service..
