### ISSUE TITLE
curl error code: 60

### ISSUE THREAD

**Issue by ppdragon16** [mkorthof/freenom-script#65]
I'm getting the error when using freenom.sh.

Command:
    freenom.sh -u [mydomain] -s [mysub] -6 -m  [myaddr]
Output:
    Error: Login token - failure (curl error code: 60)

Note: I've configured freenom_domain_id in freenom.conf (otherwise it would complain about missing domain id).

**Comment by mkorthof** [comment]
```
man curl|grep 60
       60     Peer certificate cannot be authenticated with known CA certificates.
```

As logging into my.freenom.com failed, there are no domain details are available -- including any id's.

Try connecting manually with curl, or `freenom.sh -l -debug 1`

Probably OS, (open)ssl lib and/or ca-certificates need to be updated.
