### ISSUE TITLE
Invalid AWS WAF CAPTCHA token

### ISSUE THREAD

**Issue by ChaoticWyrme** [mkorthof/freenom-script#68]
I saw the solution from the other issue, but when I copy the aws-waf-token cookie, it doesn't work and gives the error in the title.

Here's an example of a token:
e2b10ef9-70ac-4271-b025-22bd09923d0b:CgoAgqOBFeoQAAAA:UbYXNajFuWlkcHNz4fvKv57h1Bo/VST7GZWoCFZi8gzlSk/KQkkL7wcQCwE3zn+3jI/ds0nWrvSE8ZEqtjUjRzKIYeoQtnYXmCxxkQHXihV8A0mjmYXuLmqLheUfeLZ7F+l72ThzDcwKcuMwbnVQ/hh+U5jtio05tyL2jw0BbsW711cnpXZY6Z/Hja1+bZQ8DJ3H7C7HfAVCFKGO4SMuKaJhIWBEBjJSHD0ADmdyik42kkLS9vVQBKVaJ6ZJ

**Comment by tasict** [comment]
@mkorthof Please update docker image for use new version script.
