### ISSUE TITLE
Update only subdomains

### ISSUE THREAD

**Issue by P0luX3882** [mkorthof/freenom-script#7]
Hello,
I want to only update subdomains and not the domains itself, how can I do that ?

Thanks,
P0luX,

**Comment by mkorthof** [comment]
Hi,

As stated in example in help (see `freenom.sh -h` or [README.md](https://github.com/mkorthof/freenom-script/blob/master/README.md))

`./freenom.sh -u example.tk -s mail`

That will update A record of "mail.example.tk" with your ip.
